# Generated by Django 2.2.2 on 2019-06-05 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('author', models.CharField(max_length=300, null=True, verbose_name='Автор')),
                ('duration_video', models.IntegerField(default=0, null=True, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='VideoQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_time', models.DateTimeField(auto_now_add=True, verbose_name='Время выбора')),
                ('user_choices', models.IntegerField(default=1, verbose_name='Голоса')),
                ('selected_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Song', verbose_name='Выбранная песня')),
            ],
            options={
                'verbose_name': 'Песня в очереди',
                'verbose_name_plural': 'Очередь песен',
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_time', models.DateTimeField(auto_now_add=True, verbose_name='Время выбора')),
                ('VideoInQuery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.VideoQuery', verbose_name='Песня в очереди')),
                ('voted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавший пользователь')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.CreateModel(
            name='ActualSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_duration', models.IntegerField(default=0, verbose_name='Оставшееся время')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Song', verbose_name='Текущее видео')),
            ],
            options={
                'verbose_name': 'Проигрываемое видео',
                'verbose_name_plural': 'Проигрываемые видео',
            },
        ),
    ]
